### PR TITLE
Update state.go

### PR DESCRIPTION
**Pull request by treevong**
To fix an issue that node come back from inactive state not being selected to be arbitrator

### CODE REVIEW

**Comment by RainFallsSilent** [comment]
@treevong did you found some issues ？ 'producer.select' means the producer is the randomly selected DPoS node.
If one DPoS node changed to inactive after it has been randomly selected, randomly DPoS node will change to another one. So we can not change 'select' to true when we activate the DPoS node.

**Comment by treevong** [comment]
@RainFallsSilent I got the issue with my node, ThaiELA. It went offline and became inactive in block 937705. Then, I sent a transaction to activate it back in block 939577 (~60 hours ago). Since then, my node has never been pick up to be an arbitrator which I suspected that there is a bug in node selection logic.

Please kindly investigate the issue. Thank you.

**Comment by RainFallsSilent** [comment]
@treevong We have investigated the situation, and your voting rank is 24. The arbitrators is 12 CRC DPoS nodes + 24 Voting DPoS nodes, among which the last one of 24 Voting DPoS nodes is not selected by voting rank, but randomly selected from the candidate DPoS nodes. Therefore, your node may be selected randomly as a DPoS node instead of always being an arbitrator.

**Comment by treevong** [comment]
@RainFallsSilent Thank for the investigation. As you mentioned that the DPoS nodes is randomly selected, the problem is nodes that coming back from inactive status has never been selected by this random logic. You may check ThaiELA and ElaboxSN1. They've never been randomly selected since they back from inactive to active.

ThaiELA back to active since July 6 - 0298c8fe480d1f279deaada3af870affc65c8724c0c5d002d72ab184fb13047899
ElaboxSN1 back to active since July 8 - 025927918f6b7f6c42ac359a8689f0432282fbf30e40997cbb0c3b9dfe551bd43f

**Comment by RainFallsSilent** [comment]
@treevong Check that your node status is normal, only two nodes will be randomly selected every day, I think your node is just not randomly selected. There are 20 candidate nodes with the same probability of being selected, you can wait longer.

**Comment by treevong** [comment]
@RainFallsSilent thank you for the explanation. I was thinking that it randomly select all the 24 nodes every 36 blocks. Could you confirm my understanding on node selection logic?

12 CRC nodes fixed.
24 Voting nodes. Randomly selected everyday. 2 of 24 will be randomly out. Another 2 nodes that are active and not arbitrator will be randomly in.

**Comment by RainFallsSilent** [comment]
@treevong Just the last one of 24 nodes is selected by random. 23 Voting nodes selected by voting rank. 1 node will be selected randomly. We are already considering changing the consensus to be completely random, the voting rules need to be adjusted accordingly, and the proposal needs to be further discussed. After that, we need to put forward a proposal to see the views of the community. But this will not be soon, because a big consensus adjustment needs to be very cautious.

**Comment by treevong** [comment]
@RainFallsSilent I got it. Thank you for clarification.

**Pull request closed without merging**
